[project]
name = "demo-saga-pattern"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask==2.3.3",
    "flask-cors==4.0.0",
    "requests==2.31.0",
]
